// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { clientLoader as clientLoader_1 } from '/Users/kongmingming/Desktop/gate/web3/react-template/src/pages/index.tsx';
export default {
  '1': clientLoader_1,
};
