// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/kongmingming/Desktop/gate/web3/react-template/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/kongmingming/Desktop/gate/web3/react-template/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/kongmingming/Desktop/gate/web3/react-template/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/kongmingming/Desktop/gate/web3/react-template/src/.umi/plugin-locale';
export { StyleSheetManager, ThemeProvider, createGlobalStyle, css, keyframes, styled, useTheme } from '/Users/kongmingming/Desktop/gate/web3/react-template/src/.umi/plugin-styledComponents';
// plugins types.d.ts
export * from '/Users/kongmingming/Desktop/gate/web3/react-template/src/.umi/plugin-antd/types.d';
